# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Settings.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName("TabWidget")
        TabWidget.resize(651, 400)
        TabWidget.setMinimumSize(QtCore.QSize(363, 224))
        TabWidget.setMaximumSize(QtCore.QSize(680, 400))
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setAcceptDrops(False)
        self.radioButton.setAutoFillBackground(False)
        # self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout.addWidget(self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout.addWidget(self.radioButton_5)
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_6.setObjectName("radioButton_6")
        self.verticalLayout.addWidget(self.radioButton_6)

        self.radioButton_8 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_8.setObjectName("radioButton_8")
        self.verticalLayout.addWidget(self.radioButton_8)

        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton_7 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_7.setObjectName("radioButton_7")
        self.verticalLayout_2.addWidget(self.radioButton_7)
        self.radioButton_9 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_9.setObjectName("radioButton_9")
        self.verticalLayout_2.addWidget(self.radioButton_9)
        self.radioButton_11 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_11.setObjectName("radioButton_11")
        self.verticalLayout_2.addWidget(self.radioButton_11)
        self.radioButton_12 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_12.setObjectName("radioButton_12")
        self.verticalLayout_2.addWidget(self.radioButton_12)
        # ------------------------
        self.radioButton_16 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_16.setObjectName("radioButton_16")
        self.verticalLayout_2.addWidget(self.radioButton_16)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radioButton_13 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_13.setObjectName("radioButton_13")
        self.verticalLayout_3.addWidget(self.radioButton_13)
        self.radioButton_15 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_15.setObjectName("radioButton_15")
        self.verticalLayout_3.addWidget(self.radioButton_15)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_4.addWidget(self.pushButton)
        TabWidget.addTab(self.tab, "")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.radioButton_14 = QtWidgets.QRadioButton(self.tab1)
        self.radioButton_14.setObjectName("radioButton_14")
        self.verticalLayout_5.addWidget(self.radioButton_14)
        self.radioButton_10 = QtWidgets.QRadioButton(self.tab1)
        self.radioButton_10.setCheckable(True)
        # self.radioButton_10.setChecked(True)
        self.radioButton_10.setObjectName("radioButton_10")
        self.verticalLayout_5.addWidget(self.radioButton_10)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem5)
        TabWidget.addTab(self.tab1, "")

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        _translate = QtCore.QCoreApplication.translate
        TabWidget.setWindowTitle(_translate("TabWidget", "Settings"))
        self.groupBox.setTitle(_translate("TabWidget", "Полный кадр"))
        self.radioButton.setText(_translate("TabWidget", "GrayScale"))
        self.radioButton_2.setText(_translate("TabWidget", "Negative"))
        self.radioButton_3.setText(_translate("TabWidget", "Sepia"))
        self.radioButton_4.setText(_translate("TabWidget", "Blue Sepia"))
        self.radioButton_5.setText(_translate("TabWidget", "Gradient"))
        self.radioButton_6.setText(_translate("TabWidget", "Noise"))
        self.radioButton_8.setText(_translate("TabWidget", "None"))  # <---
        self.groupBox_2.setTitle(_translate("TabWidget", "Части кадра"))
        self.radioButton_7.setText(_translate("TabWidget", "Контуры в кадре"))
        self.radioButton_9.setText(_translate("TabWidget", "Поиск людей"))
        self.radioButton_11.setText(_translate("TabWidget", "Силуэт тренера"))
        self.radioButton_11.setEnabled(False)
        self.radioButton_12.setText(_translate("TabWidget", "Контур тренера"))
        self.radioButton_16.setText(_translate("TabWidget", "None"))
        self.groupBox_3.setTitle(_translate("TabWidget", "Остальное"))
        self.radioButton_13.setText(_translate("TabWidget", "Deep Dream"))
        self.radioButton_13.setEnabled(False)
        self.radioButton_15.setText(_translate("TabWidget", "Waking Life"))
        self.radioButton_15.setEnabled(False)
        self.label_2.setText(_translate("TabWidget", "Start:"))
        self.label_3.setText(_translate("TabWidget", "End:"))
        self.pushButton.setText(_translate("TabWidget", "Confirm and cancel"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab), _translate("TabWidget", "Video"))

        self.radioButton_14.setText(_translate("TabWidget", "Искажение"))
        self.radioButton_10.setText(_translate("TabWidget", "None"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab1), _translate("TabWidget", "Audio"))

